import { Organization, Claim, Document, Opportunity } from './types';
import { v4 as uuidv4 } from 'uuid';

const CEC_ORG_ID = '00000000-0000-4000-8000-000000000001';

export const SEED_ORG: Organization = {
  id: CEC_ORG_ID,
  name: 'Community Environmental Council',
  slug: 'cec',
  description: 'CEC is a Santa Barbara-based environmental nonprofit working across regenerative agriculture, community solar, policy advocacy, and regional sustainability initiatives since 1970.',
  website: 'https://cecsb.org',
  location: 'Santa Barbara County, California',
  focus_areas: ['solar_energy', 'regenerative_agriculture', 'transportation_electrification', 'policy_advocacy', 'community_engagement'],
  created_at: new Date().toISOString(),
};

const claimIds = Array.from({ length: 8 }, () => uuidv4());

export const SEED_CLAIMS: Claim[] = [
  {
    id: claimIds[0],
    org_id: CEC_ORG_ID,
    narrative: 'Facilitated transition of 22 farms to regenerative agriculture practices in Santa Barbara and Ventura Counties between 2021-2023',
    claim_type: 'ecological',
    status: 'self_reported',
    quantity: '22',
    quantity_unit: 'farms',
    start_date: '2021',
    end_date: '2023',
    location: 'Santa Barbara and Ventura Counties, CA',
    theme_tags: ['regenerative_agriculture'],
    sdg_tags: ['SDG2', 'SDG15'],
    ai_confidence: 0.92,
    source_document: 'CEC Annual Report 2023',
    source_section: 'Regenerative Agriculture Program',
    evidence_summary: 'Documented farm-by-farm transition records with practice adoption metrics',
    human_reviewed: true,
    ledger_anchored: false,
    created_at: new Date('2024-01-15').toISOString(),
  },
  {
    id: claimIds[1],
    org_id: CEC_ORG_ID,
    narrative: 'Installed 3.4 MW of community solar capacity serving 840 low-income households in Santa Barbara County',
    claim_type: 'ecological',
    status: 'self_reported',
    quantity: '3.4',
    quantity_unit: 'MW',
    location: 'Santa Barbara County, CA',
    theme_tags: ['solar_energy'],
    sdg_tags: ['SDG7', 'SDG10'],
    ai_confidence: 0.95,
    source_document: 'CEC Solar Program Report 2023',
    source_section: 'Community Solar Installations',
    evidence_summary: 'Installation records, utility interconnection agreements, household enrollment data',
    human_reviewed: true,
    ledger_anchored: false,
    created_at: new Date('2024-01-15').toISOString(),
  },
  {
    id: claimIds[2],
    org_id: CEC_ORG_ID,
    narrative: 'Reduced greenhouse gas emissions by an estimated 4,200 metric tons CO2e through solar and electrification programs in 2022',
    claim_type: 'ecological',
    status: 'self_reported',
    quantity: '4200',
    quantity_unit: 'metric tons CO2e',
    start_date: '2022',
    end_date: '2022',
    theme_tags: ['solar_energy', 'carbon'],
    sdg_tags: ['SDG13'],
    ai_confidence: 0.85,
    source_document: 'CEC Annual Report 2022',
    source_section: 'Climate Impact Summary',
    evidence_summary: 'Estimated from solar generation data and fleet electrification records using EPA emission factors',
    human_reviewed: false,
    ledger_anchored: false,
    created_at: new Date('2024-02-01').toISOString(),
  },
  {
    id: claimIds[3],
    org_id: CEC_ORG_ID,
    narrative: 'Engaged 6,800 community members through environmental education and outreach programs in 2022-2023',
    claim_type: 'social',
    status: 'self_reported',
    quantity: '6800',
    quantity_unit: 'community members',
    start_date: '2022',
    end_date: '2023',
    location: 'Santa Barbara County, CA',
    theme_tags: ['community_engagement', 'education'],
    sdg_tags: ['SDG4', 'SDG11'],
    ai_confidence: 0.88,
    source_document: 'CEC Annual Report 2023',
    source_section: 'Community Engagement',
    evidence_summary: 'Event attendance records, workshop sign-ins, program participation logs',
    human_reviewed: true,
    ledger_anchored: false,
    created_at: new Date('2024-02-15').toISOString(),
  },
  {
    id: claimIds[4],
    org_id: CEC_ORG_ID,
    narrative: 'Transitioned 145 vehicles to electric in partnership with municipal and commercial fleet operators',
    claim_type: 'ecological',
    status: 'self_reported',
    quantity: '145',
    quantity_unit: 'vehicles',
    theme_tags: ['transportation_electrification'],
    sdg_tags: ['SDG13', 'SDG11'],
    ai_confidence: 0.9,
    source_document: 'CEC Fleet Electrification Report',
    source_section: 'Vehicle Transition Summary',
    evidence_summary: 'Fleet operator agreements and vehicle registration records',
    human_reviewed: false,
    ledger_anchored: false,
    created_at: new Date('2024-03-01').toISOString(),
  },
  {
    id: claimIds[5],
    org_id: CEC_ORG_ID,
    narrative: 'Supported adoption of cover cropping on 890 acres across partner farms in the region',
    claim_type: 'ecological',
    status: 'self_reported',
    quantity: '890',
    quantity_unit: 'acres',
    theme_tags: ['regenerative_agriculture', 'carbon'],
    sdg_tags: ['SDG15', 'SDG2'],
    ai_confidence: 0.87,
    source_document: 'CEC Regen Ag Report 2023',
    source_section: 'Cover Cropping Program',
    evidence_summary: 'Farm-level acreage records and practice verification surveys',
    human_reviewed: false,
    ledger_anchored: false,
    created_at: new Date('2024-03-15').toISOString(),
  },
  {
    id: claimIds[6],
    org_id: CEC_ORG_ID,
    narrative: 'Secured $2.1M in clean energy incentives and rebates for low-income households and small businesses',
    claim_type: 'financial',
    status: 'self_reported',
    quantity: '2100000',
    quantity_unit: 'USD',
    theme_tags: ['solar_energy', 'community_engagement'],
    sdg_tags: ['SDG1', 'SDG7'],
    ai_confidence: 0.93,
    source_document: 'CEC Financial Impact Report 2023',
    source_section: 'Incentives and Rebates',
    evidence_summary: 'Utility rebate records, state incentive program documentation, household verification',
    human_reviewed: true,
    ledger_anchored: false,
    created_at: new Date('2024-04-01').toISOString(),
  },
  {
    id: claimIds[7],
    org_id: CEC_ORG_ID,
    narrative: 'Partnered with 3 indigenous land management organizations on traditional ecological knowledge integration in regenerative agriculture programming',
    claim_type: 'governance',
    status: 'self_reported',
    quantity: '3',
    quantity_unit: 'organizations',
    theme_tags: ['regenerative_agriculture', 'policy_advocacy'],
    sdg_tags: ['SDG15', 'SDG17'],
    ai_confidence: 0.82,
    source_document: 'CEC Partnership Report 2023',
    source_section: 'Indigenous Partnerships',
    evidence_summary: 'MOU documents and program co-design records',
    human_reviewed: false,
    ledger_anchored: false,
    created_at: new Date('2024-04-15').toISOString(),
  },
];

const SEED_OPP_ID = '00000000-0000-4000-8000-000000000010';

export const SEED_OPPORTUNITY: Opportunity = {
  id: SEED_OPP_ID,
  org_id: CEC_ORG_ID,
  name: 'USDA Partnerships for Climate-Smart Commodities',
  funder: 'USDA',
  description: 'Funding for projects that produce, market, and measure climate benefits of commodities produced through climate-smart practices.',
  amount: '$250,000 - $2,000,000',
  deadline: 'April 15, 2026',
  requirements: [
    { requirement: 'Project must involve agricultural producers and activities on working lands', type: 'eligibility', critical: true },
    { requirement: 'Must demonstrate measurable GHG reductions or carbon sequestration with quantified metrics', type: 'data', critical: true },
    { requirement: 'Must include market development activities for climate-smart commodities', type: 'thematic', critical: true },
    { requirement: 'Preference for projects serving underserved and small/mid-size producers', type: 'eligibility', critical: false },
    { requirement: 'Must include robust monitoring, reporting, and verification (MRV) plan', type: 'reporting', critical: true },
    { requirement: 'Partnership with at least one underserved community or producer group', type: 'eligibility', critical: false },
    { requirement: 'Documentation of baseline conditions and projected impacts', type: 'data', critical: true },
  ],
  source_document: 'USDA PCSC RFP 2026',
  created_at: new Date('2024-05-01').toISOString(),
};

export const SEED_DOCUMENTS: Document[] = [
  {
    id: uuidv4(),
    org_id: CEC_ORG_ID,
    filename: 'CEC Annual Report 2023.pdf',
    doc_type: 'annual_report',
    upload_date: new Date('2024-01-15').toISOString(),
    claims_extracted: 4,
    status: 'complete',
  },
  {
    id: uuidv4(),
    org_id: CEC_ORG_ID,
    filename: 'CEC Solar Program Report 2023.pdf',
    doc_type: 'monitoring_report',
    upload_date: new Date('2024-01-15').toISOString(),
    claims_extracted: 2,
    status: 'complete',
  },
  {
    id: uuidv4(),
    org_id: CEC_ORG_ID,
    filename: 'CEC Fleet Electrification Report.pdf',
    doc_type: 'monitoring_report',
    upload_date: new Date('2024-03-01').toISOString(),
    claims_extracted: 1,
    status: 'complete',
  },
  {
    id: uuidv4(),
    org_id: CEC_ORG_ID,
    filename: 'CEC Partnership Report 2023.pdf',
    doc_type: 'other',
    upload_date: new Date('2024-04-15').toISOString(),
    claims_extracted: 1,
    status: 'complete',
  },
];

export { CEC_ORG_ID };
